name: Bump patch version

on:
  push:
    branches: [ npm ]

jobs:
  build-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Bump patch version
        run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "GitHub Actions"
          npm version patch
          git status
          package_version=`node -p "require('./package.json').version"`
          echo "PACKAGE_VERSION=${package_version}" >> $GITHUB_ENV
        shell: bash

      - name: Create Bump patch version Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'ci: bump patch version to ${{ env.PACKAGE_VERSION }}'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: '[Release BOT] Bump patch version to ${{ env.PACKAGE_VERSION }}'
          body: |
            Bump patch version to ${{ env.PACKAGE_VERSION }}
            - Auto-generated by `bump-patch-version.yml` action
            - Triggered ad you pushed some changes to npm branch
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"