name: Generating WIKI API Docs in github wiki

on:
  push:
    branches: [ main ]

jobs:
  build-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: srcRepo
      - name: Building wiki
        run: |
          pwd
          ls -al
          cd srcRepo
          npm ci
          npm run createJSDocs
          ls -al docs
        shell: bash

      - uses: actions/checkout@v4
        with:
           repository: ${{github.repository}}.wiki    # specify the wiki repo name here.
           path: wiki
      - name: copying generated API doc files to wiki
        run: |
          pwd
          mkdir -p ./wiki/generatedDocs
          rm -rf ./wiki/generatedDocs/*
          rsync -a ./srcRepo/docs/ ./wiki/generatedDocs
          find ./wiki
          cd wiki
          git add .
          git status
        shell: bash

      - name: Commit new wiki files
        run: |
          pwd
          cd wiki
          git config --local user.email "action@github.com"
          git config --local user.name "phoenixide"
          git add .
          git diff-index --quiet HEAD || git commit -m "Adding API docs: ${{ github.event.pull_request.title }}"
          git log -1 --stat
        shell: bash

      - name: Push changes to Github wiki
        uses: ad-m/github-push-action@master
        with:
          repository: ${{github.repository}}.wiki
          branch: master
          directory: wiki
          github_token: ${{ secrets.GITHUB_TOKEN }}
